# Generated by Django 2.0 on 2018-05-25 03:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptNo', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('loc', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'dept',
            },
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empNo', models.AutoField(primary_key=True, serialize=False)),
                ('ename', models.CharField(db_index=True, max_length=20)),
                ('job', models.CharField(max_length=20, null=True)),
                ('hireDate', models.DateField(null=True)),
                ('sal', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('comm', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男')], null=True)),
                ('isValid', models.IntegerField(choices=[(0, '无效'), (1, '有效')], db_column='is_valid', default=1)),
                ('dept', models.ForeignKey(db_column='deptno', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Dept')),
                ('mgr', models.ForeignKey(db_column='mgr', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Emp')),
            ],
            options={
                'db_table': 'emp',
            },
            managers=[
                ('emps', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SalGrade',
            fields=[
                ('grade', models.AutoField(primary_key=True, serialize=False)),
                ('lowsal', models.IntegerField()),
                ('higsal', models.IntegerField()),
            ],
            options={
                'db_table': 'salegrade',
            },
        ),
    ]
