# Generated by Django 2.0 on 2018-05-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='emp',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='emp',
            name='dept',
            field=models.ForeignKey(db_column='deptno', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Dept'),
        ),
    ]
