# Generated by Django 2.0 on 2018-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='slug',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='slugUrl',
            field=models.SlugField(db_column='slug_url', default=''),
        ),
    ]
